### ISSUE TITLE
DDD improvements, applying Onion/Hexagonal architecture

### ISSUE THREAD

**Issue by mxr576** [php-tuf/composer-stager#13]
Hi,

First of all, super exciting project and I already like the design and code quality in it. I would like to promote this as learning material for others.
Although, I have some ideas how to further improve it, how to adapt [Onion](https://blog.itsjavi.com/target-software-architectures-the-onion-architecture)/Hexagonal architecture deeper, like:
* introducing new value objects (e.g.: for paths, those should be clearly local references only if I am not mistaken, but currently they are just `string`s)
* decoupling from the Symfony Command library too, like the code is already decoupled from Filesystem, and supporting other presentation layers (like other CLI libs)
* narrowing down the public API of this library, like `FileCopierInterface` is the generic API that could be extended, `RsyncFileCopierInterface` and `SymfonyFileCopierInterface` are empty currently and they are infrastructure specific, so they are probably unnecessary.
* ...

What do you think? Are you open to PR-s with changes like these and having discussions about them?

**Comment by TravisCarden** [comment]
Hello, @mxr576. Nice to meet you!

> I already like the design and code quality in it.

Thank you. That's very encouraging. 🙂 

> I would like to promote this as learning material for others.

I don't know exactly what you have in mind, but as a strong advocate of mentorship and continuous learning it sounds exciting.

> I have some ideas how to further improve it, how to adapt Onion/Hexagonal architecture deeper... Are you open to PR-s with changes like these and having discussions about them?

Yes, I'm definitely open to this. I'm still learning Domain Driven Development, and I would be very happy to receive feedback. As early as we are in development, there's still a lot of redesign and refactoring going on concurrent with feature development, so we would need to take care not to create conflicts or duplicate effort. I have some requirements for all new code:

* Obviously, all the tests and static analysis must pass.
* All code must have full (meaningful) test coverage. I'm proud of the fact that I've maintained 100% coverage from the beginning; and especially given the sensitive context of this project, I'm not willing to compromise on that. I observe the standard [Test Pyramid](https://martinfowler.com/bliki/TestPyramid.html). I require entire unit test coverage except where conditions cannot be readily simulated in unit tests, such as filesystem failures.
* In addition to the standard quality scans, I have a number of custom PHPStan rules that enforce design policies. Changes or exceptions to these policies must be discussed.
* All code must have good documentation. This is highly subjective, of course, and I haven't decided on all patterns (such as which docblock annotations are required and when). I would love input here. Discussions should take place in in https://github.com/php-tuf/phpcodesniffer-standard.
* Good public APIs and developer experience must be constantly maintained or improved.
* Code readability and maintainability must be high.

I suspect you would already support most of these. 🙂 

With that, feel free to open issues to discuss individual proposals. Thanks!

**Comment by TravisCarden** [comment]
FYI, @mxr576, I think you will find the code as of https://github.com/php-tuf/composer-stager/releases/tag/v1.0.0 a much more complete application of DDD principles. I hope you like it. 😉
