### ISSUE TITLE
Directory permissions are not correct when using the PHP file syncer

### ISSUE THREAD

**Issue by tedbow** [php-tuf/composer-stager#175]
Discovered here https://www.drupal.org/project/automatic_updates/issues/3362143#comment-15083985

but will copy relevant comment: 

>I traced into this, and what I found was straightforward: when the stage directory is created, sites/default (the directory) has different permissions depending on whether the file syncer is rsync, or the PHP syncer.
>
> In the active directory, the permissions are 644. That's because Drupal actively tries to write-protect the directory (it does this at install time, and in `system_requirements()`) for security hardening. Makes sense.
> 
> Now, if you're using the rsync file syncer, those permissions are preserved when the stage directory is created. That's because Composer Stager calls rsync with the `--archive` option, which implies the `--perms` option, which preserves permissions. Because of that, the scaffold files cannot be updated in `sites/default`, and the update fails due to `ScaffoldFilePermissionsValidator`. Makes sense.
> 
> The PHP file syncer, as it turns out, is less reliable. It delegates to Symfony's Filesystem component (specifically the `\Symfony\Component\Filesystem\Filesystem::copy()` method), which does try to preserve permissions on copied files...but it does not preserve permissions on directories. When creating directories, it does this:
> 
> ```$this->mkdir(\dirname($targetFile));```
> 
> `\Symfony\Component\Filesystem\Filesystem::mkdir()` takes a second argument -- the permissions, which default to 777. But `copy()` doesn't pass that argument, so the directory is created with 777 permissions.
> 
> This causes our build tests, which use the PHP file syncer by default, to pass by coincidence. As it turns out, we do try to ensure that we're handling permissions of sites/default properly -- if you look at `\Drupal\Tests\automatic_updates\Build\CoreUpdateTest::createTestProject()`, this is the last bit of the method:
> 
>     // Ensure that Drupal has write-protected the site directory.
>     $this->assertDirectoryIsNotWritable($this->getWebRoot() . '/sites/default');
> What we didn't realize, though, is that the PHP file syncer is disregarding those permissions, and creating the staged copy of sites/default with world-writable permissions. So this test is wrongfully, but understandably, assuming that the permissions from the active sites/default directory are reflected in the staged sites/default.

**Comment by tedbow** [comment]
@phenaproxima discovered this

**Comment by tedbow** [comment]
I have confirmed this problem with https://github.com/php-tuf/composer-stager-console
I just edited `\PhpTuf\ComposerStager\Internal\FileSyncer\Factory\FileSyncerFactory` directly to switch between the rsync and php file copiers.

I tested using a sub folder with `rwxr---r--` permissions.

When using the php  file copy.
1. on begin the staging area this folder was created with permissions  `rwxr--xr-x`

**Comment by TravisCarden** [comment]
I've been working on fixing this, but having concluded that the PHP file syncer is likely to be a never ending source of issues like this one, I floated the idea of obviating the whole problem in [Create a separate rsync shim Composer library for Composer Stager [#3415948] | Drupal.org](https://www.drupal.org/project/drupal/issues/3415948).

**Comment by TravisCarden** [comment]
@tedbow per the above PR, `rsync` support has been added for Windows, and `PhpFileSyncer` has been eliminated, rendering this issue obsolete. Closing. Thanks!
