### ISSUE TITLE
rsync file syncer excludes directories by name, rather than by relative path

### ISSUE THREAD

**Issue by phenaproxima** [php-tuf/composer-stager#183]
This is what happens when you roll a natural 1 on arcana (D&D nerds, rejoice).

Let's say we have a directory tree like this:

```
src/
tests/
  src/
```

If we want to exclude the top-level `src` directory from a Composer Stager operation, we would pass `src` as an excluded path. This is in accordance with the documentation of the file syncer interface, which states that exclusions should be passed as relative paths.

However, the rsync file syncer will pass that to rsync as `--exclude=src`. Which, it turns out, will cause ALL the `src` directories in the tree to be excluded! It seems that `--exclude` follows (essentially) the same rules as `.gitignore`. In a gitignore file, if you wanted to exclude the top-level `src` directory, you'd refer to it as `/src`. Indeed, if you pass `--exclude=/src` to rsync, it behaves correctly.

So I'm thinking that the rsync file syncer should probably _always_ prefix excluded paths with `/`, so as to make it behave as the interface documentation says it will.

But, you're asking, what if you pass a fully absolute path? My guess -- which I have not tested -- is that it treats it as relative to the source directory. So, if you pass `/path/to/my/stuff`, and your source directory happens to contain a path like `path/to/my/stuff`, it'll be excluded. But if you pass an absolute path that does NOT map neatly into the source directory tree like that, I'm assuming it'll just be ignored, which is totally fine.

**Comment by wimleers** [comment]
Drupal.org issue: https://www.drupal.org/project/automatic_updates/issues/3365151.

**Comment by TravisCarden** [comment]
@phenaproxima, I believe I've fixed this in the above-linked PR. Can you verify it for me? I pushed it up to the `wip` branch for you. (`composer require php-tuf/composer-stager:dev-wip`)

**Comment by phenaproxima** [comment]
Sure, @TravisCarden. I'll give it a shot.

**Comment by phenaproxima** [comment]
I tested this manually with 2.0-alpha1 and confirmed that, if there's a top-level `src` directory, the bug happens. Then I tested with the `wip` branch in your fork and confirmed that it works.

So consider this one good to go! (Ideally there are functional tests of it too.)

**Comment by TravisCarden** [comment]
> I tested this manually... and confirmed that it works. So consider this one good to go! (Ideally there are functional tests of it too.)

Yay, thank you! And yes, the functional tests were added to the end-to-end test cases. (I'd like to add an _isolated_ functional test, too, but I was having a hard time getting my fixture to work. Maybe later.)

Merging. We can cut a `v2.0.0-alpha2` whenever you're ready.
