### ISSUE TITLE
check if `set_time_limit` is available before calling it

### ISSUE THREAD

**Issue by tedbow** [php-tuf/composer-stager#253]
In several places like `\PhpTuf\ComposerStager\Internal\FileSyncer\Service\PhpFileSyncer::sync` `set_time_limit()` is called. But this might be disabled on some hosting. On drupal/automatic_updates we want to make sure we will work in this type of hosting. So I was trying to make build test in https://www.drupal.org/project/automatic_updates/issues/3381294#comment-15193112 that disables this function before it starts up the server and sets `max_execution_time` low. 

Could composer-stager check if `set_time_limit` is available before calling it. Thanks

**Comment by tedbow** [comment]
This is the error that comes throw on the drupal side

> Drupal\package_manager\Exception\StageException: Call to undefined function PhpTuf\ComposerStager\Internal\FileSyncer\Service\set_time_limit() in Drupal\package_manager\StageBase->rethrowAsStageException() (line 350 of modules/contrib/automatic_updates/package_manager/src/StageBase.php).
PhpTuf\ComposerStager\Internal\Core\Beginner->begin(Object, Object, Object, NULL, 300) (Line: 333)
Drupal\package_manager\StageBase->create(300) (Line: 117)
Drupal\automatic_updates\UpdateStage->begin(Array) (Line: 82)
Drupal\automatic_updates\BatchProcessor::begin(Array, Array) (Line: 295)
_batch_process() (Line: 186)
_batch_progress_page() (Line: 86)
_batch_page(Object) (Line: 55)
Drupal\system\Controller\BatchController->batchPage(Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 580)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 163)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 74)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object, 1, 1) (Line: 692)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
require('/private/tmp/build_workspace_56982179a25fb2843c6d7fe4067a389dlEm4Pt/project/web/index.php') (Line: 71)

**Comment by TravisCarden** [comment]
^ Fixed, @tedbow. It's in `develop`. Thanks!
