### ISSUE TITLE
Use the Composer process runner internally when running Composer commands

### ISSUE THREAD

**Issue by phenaproxima** [php-tuf/composer-stager#348]
In `\PhpTuf\ComposerStager\Internal\Precondition\Service\ComposerIsAvailable`, and possibly other places, we're doing stuff like this:

```
            return $this->processFactory->create([
                $this->executablePath,
                'list',
                '--format=json',
            ]);
```

It would be preferable to use the Composer process runner to invoke Composer commands internally, rather than the process factory, since that way, Package Manager could set additional environment variables for Composer commands specifically, rather than needing to have our process factory determine if we're about to invoke Composer, and changing things then.

**Comment by TravisCarden** [comment]
Thanks, @phenaproxima. Let me think a little about the best way to approach this.

**Comment by TravisCarden** [comment]
There you go, @phenaproxima. Enjoy. 🙂
