### ISSUE TITLE
Pass `--checksum` to rsync

### ISSUE THREAD

**Issue by phenaproxima** [php-tuf/composer-stager#364]
In some cases, rsync can miss changed files if they're the same size and have the same modification time, but different contents.

To test:

* In a directory, create a file with some random data in it.
* Clone the directory and change ONE character in the cloned file.
* Ensure the two files have the same modification time (`touch()` can do this).
* rsync the cloned directory back into the original directory. It SHOULD recognize that the file has changed.

**Comment by TravisCarden** [comment]
I did some testing to compare the performance of `--checksum` with `--ignore-times` (below), and `--checksum` seems like it has the best balance; so I'll move forward with that as discussed. Thanks for the steps to reproduce.

![benchmark](https://github.com/php-tuf/composer-stager/assets/959246/d8214d73-6f93-405e-af3c-ed0d70d73b9a)

**Comment by TravisCarden** [comment]
Fixed and released: https://github.com/php-tuf/composer-stager/releases/tag/v2.0.0-rc2. Thanks again for the steps to reproduce, @phenaproxima. This was the easiest bug I fixed all day. 😄
