### ISSUE TITLE
Add support for select symlink types

### ISSUE THREAD

**Issue by TravisCarden** [php-tuf/composer-stager#58]
Currently all symlinks are forbidden. But some kinds are essentially safe and can be permitted, as discussed at length here: https://www.drupal.org/project/automatic_updates/issues/3319507

This issue will allow symlinks according to the following rules:

* **Absolute links are disallowed.** - An absolute link in the active directory will point to the same path on disk when copied to the staging directory, creating the possibility of staged operations changing production assets.
* **Hard links are disallowed.** - Hard links point to inodes as opposed to mere paths, i.e., the actual data blocks on the disk. Therefore, a hard link to a file essentially _is_ that file. So anything done to one is done to the other, with the same net effect as absolute links.
* **No symlinks of any kind are allowed on Windows.** - Most Linux flavors will let you create a symlink pointing to a path that does not exist, but Windows will fail. This creates a temporal coupling that cannot be guaranteed. Given a symlink `link.txt` with a target `target.txt`, we would have to make sure that `target.txt` was always written first (which is infeasible) or the operation would fail, leaving the codebase in some state of corruption.
* **No links that point outside the codebase root are allowed.** - Active and staging directories adjacent to one another on the filesystem have identical ancestors by definition. Hence, a relative link pointing out of one would target the same file as said link when copied "next door" and, like previous scenarios, create the possibility of corrupting accidentally shared assets.

All other symlinks are allowed.

**Comment by wimleers** [comment]
> All other symlinks are allowed.
To make this more concrete, because some may be wondering after that list "so what symlinks _are_ allowed?" … the most common use case is to have relative symlinks _within_ a composer package ("intra" aka inside, not "inter" aka between). For example: a logo that is stored once, and then symlinked for the user-facing documentation, for CSS …
