### ISSUE TITLE
Eliminate dependency on Symfony Filesystem?

### ISSUE THREAD

**Issue by TravisCarden** [php-tuf/composer-stager#60]
Should we remove Composer Stager's dependency on [`symfony/filesystem`](https://packagist.org/packages/symfony/filesystem)? Keeping it would result in a new production dependency for Drupal core. We could replace it with custom code. Or we could keep it and replace our custom path-handling code with functionality added in the latest versions of the Symfony library. This is the trade-off, in short:

|  | Dependencies | Custom code | Code changes/effort |
|---|---|---|---|
| **Keep it** | 😢 Adds one | 😍 Less | 😍 Elimination & refactoring |
| **Remove it** | 😍 None | 😢 More | 😢 Addition & refactoring |

**Comment by wimleers** [comment]
Given `symfony/config` is required and `symfony/config` requires `symfony/filesystem`, are you sure this is necessary?

See https://github.com/symfony/config/blob/6.2/composer.json#L21.

_I discovered this earlier today at https://www.drupal.org/project/drupal/issues/3326246#comment-14944593._

**Comment by TravisCarden** [comment]
Hmm. Well, we're making pretty minimal use of it (`symfony/filesystem`). We can weigh the pros and cons when we get here.

**Comment by effulgentsia** [comment]
> Given symfony/config is required and symfony/config requires symfony/filesystem, are you sure this is necessary?

At least for Composer Stager, symfony/config is only a dev dependency, so I think removing a production dependency on symfony/filesystem has merit. For Drupal, it might be moot if we end up needing/wanting to add symfony/config as a production dependency for Drupal core, but since we haven't done that yet, even for Drupal this is not yet moot.

**Comment by wimleers** [comment]
Looks like Drupal won't be adopting `symfony/config`, so … relevant once again 😅

**Comment by larowlan** [comment]
Personally I would defer to a battle-hardened library instead of writing your own, especially w.r.t file system operations. That's my 2c

**Comment by TravisCarden** [comment]
Naturally, I share the preference for using widely-used, well-tested libraries. It occurs to me that we would (should) be able to eliminate our current path-handling--the most complex code currently in our codebase--with the new path functionality in Symfony Filesystem, which changes the value proposition a little. I've updated the issue description with details. From the perspective of Composer Stager, it would probably be preferable to keep the Symfony Filesystem dependency and in fact leverage it more fully. The only question is whether it would be a good tradeoff from Drupal's perspective. Whom shall we escalate the question to?

**Comment by wimleers** [comment]
Asked release managers @xjm and @catch56 in Drupal Slack:

> @catch @xjm So for php-tuf/composer-stager, we were trying to eliminate the symfony/filesystem dependency. But then @larowlan rightfully pointed out:
>> Personally I would defer to a battle-hardened library instead of writing your own, especially w.r.t file system operations. That’s my 2c
> … so which way do we want it to go? Either:
> 1.  symfony/filesystem must become a dependency of Drupal core (it already is a dev dependency!)
> 2. php-tuf/composer-stager contains less battle-hardened filesystem-related logic
> 
> See https://github.com/php-tuf/composer-stager/issues/60

Let's find out 😊

**Comment by wimleers** [comment]
@catch56 responded in the aforementioned Drupal Slack thread:
>  given it's Symfony and looks like just a couple of classes with utility methods seems OK to move it to a production dependency but if we do so we should see what we can replace with it.

I responded to that:
> AFAICT `\Drupal\Component\FileSystem\FileSystem` remains relevant, and even `\Drupal\Core\File\FileSystem` remains relevant (because it supports stream wrappers, and Symfony’s does not). But `\Drupal\Core\File\FileSystem` could start using some of the logic in Symfony’s filesystem component I think.

@larowlan looped in @kimpepper in that Drupal Slack thread, and he chimed in:
> I proposed using symfony/filesystem back before moving a lot of stuff out of file.inc and file.module
> our filesystem implementation supports streamwrappers but also we have some settings that get used too
> I also remember someone doing a performance comparison on directory scanning a while back, and found our implementation faster.
> Our filesystem _component_ has zero dependencies, but only has one method `getOsTemporaryDirectory()`
> so I see symfony/filesystem being more useful as a component rather than being able to replace code in `\Drupal\Core\File\FileSystem`

To which @catch56 responded:
> given ^^ I do not really have a strong opinion tbh. It seems like a small dependency to add but also not one we'd use much

So AFAICT … that means there's nothing left to be done here!

I'm asking @catch56 to formally confirm that here.

**Comment by catch56** [comment]
Yeah I am fine either way, we can always try to remove it later on.
