### ISSUE TITLE
Evaluate the slevomat/coding-standard dev dependency

### ISSUE THREAD

**Issue by TravisCarden** [php-tuf/composer-stager#77]
- Part of https://github.com/php-tuf/composer-stager/issues/78.

|  |  |
|---|---|
| **Dependency** | [`slevomat/coding-standard`](https://packagist.org/packages/slevomat/coding-standard) |
| **Description** | Slevomat Coding Standard for PHP_CodeSniffer provides sniffs that fall into three categories:<ul><li>Functional - improving the safety and behavior of code</li><li>Cleaning - detecting dead code</li><li>Formatting - rules for consistent code looks</li></ul> |
| **Value/justification** | High. It provides all the usual benefits of coding standards of improving maintainability and reducing cognitive load and goes further to actually catch certain defects. See [`phpcs.xml.dist`](https://github.com/php-tuf/composer-stager/blob/v1.2.1/phpcs.xml.dist). |
| **Usage/popularity** | High. Currently over 8M installs and 1K dependents on Packagist. |
| **Security policy** | Apparently none. Requested one at https://github.com/slevomat/coding-standard/issues/1525 |
| **Maintainance** | Very active. Responsive maintainers. Frequent, well-documented releases adhere strictly to Semver. |
| **Considerations** | <ul><li>It has very thorough [user documentation](https://github.com/slevomat/coding-standard).</li><li>[The Drupal Coder module](https://www.drupal.org/project/coder) already uses it: https://git.drupalcode.org/project/coder/-/blob/8.3.17/composer.json#L21</li></ul> |

### Dependency tree

```
$ composer info --tree slevomat/coding-standard
slevomat/coding-standard 8.8.0 Slevomat Coding Standard for PHP_CodeSniffer complements Consistence Coding Standard by providing sniffs with additional checks.
|--dealerdirect/phpcodesniffer-composer-installer ^0.6.2 || ^0.7 || ^1.0
|  |--composer-plugin-api ^1.0 || ^2.0
|  |--php >=5.4
|  `--squizlabs/php_codesniffer ^2.0 || ^3.1.0 || ^4.0
|     |--ext-simplexml *
|     |--ext-tokenizer *
|     |--ext-xmlwriter *
|     `--php >=5.4.0
|--php ^7.2 || ^8.0
|--phpstan/phpdoc-parser >=1.15.2 <1.16.0
|  `--php ^7.2 || ^8.0
`--squizlabs/php_codesniffer ^3.7.1
   |--ext-simplexml *
   |--ext-tokenizer *
   |--ext-xmlwriter *
   `--php >=5.4.0
```

**Comment by effulgentsia** [comment]
`slevomat/coding-standard` is already a Drupal core dev dependency via `drupal/coder` and is already listed in https://www.drupal.org/about/core/policies/core-dependency-policies/dependency-info#coding-standard, so closing this issue.
