### ISSUE TITLE
Evaluate the `symfony/config` dev dependency

### ISSUE THREAD

**Issue by TravisCarden** [php-tuf/composer-stager#81]
- Part of https://github.com/php-tuf/composer-stager/issues/78.

|  |  |
|---|---|
| **Dependency** | [`symfony/config`](https://packagist.org/packages/symfony/config) |
| **Description** | Helps you find, load, combine, autofill and validate configuration values of any kind. |
| **Value/justification** | Indispensable. This is used for service autoloading in tests, which is not only convenient but actually exercises the API as it would be used by clients. |
| **Usage/popularity** | Extremely high. Currently over 225M installs and 5K dependents on Packagist. |
| **Security policy** | https://github.com/symfony/config/security/policy |
| **Maintainance** | The maintenance details for all Symfony components are the same and have already been evaluated for inclusion of others in Drupal core. |
| **Considerations** | <ul><li>Drupal core may already be going to add `symfony/config` to its own dependencies: [Use native Symfony YamlLoader + Config [#3111008]](https://www.drupal.org/project/drupal/issues/3111008)</li><li>Could possibly be eliminated by converting the services configuration to XML, if desirable.</li></ul> |

### Dependency tree

```
$ composer info --tree symfony/config
symfony/config v6.2.7 Helps you find, load, combine, autofill and validate configuration values of any kind
|--php >=8.1
|--symfony/deprecation-contracts ^2.1|^3
|  `--php >=8.1
|--symfony/filesystem ^5.4|^6.0
|  |--php >=8.1
|  |--symfony/polyfill-ctype ~1.8
|  |  `--php >=7.1
|  `--symfony/polyfill-mbstring ~1.8
|     `--php >=7.1
`--symfony/polyfill-ctype ~1.8
   `--php >=7.1

```

**Comment by effulgentsia** [comment]
I think it's quite sensible to leave `symfony/config` as a dev dependency of Composer Stager.

```
Drupal core may already be going to add symfony/config to its own dependencies. (Citation?)
```
https://www.drupal.org/project/drupal/issues/3111008 is the issue for that. That issue still has challenges to work through, but that's related to using `symfony/config` at runtime and reconciling the remaining differences between how Symfony builds the service container vs. how Drupal currently builds it. But none of those concerns are reasons to not use `symfony/config` as a dev dependency of this package.
