### ISSUE TITLE
Symlinks to directories don't work with PhpFileSyncer

### ISSUE THREAD

**Issue by phenaproxima** [php-tuf/composer-stager#99]
While working on https://www.drupal.org/project/automatic_updates/issues/3319507, I created a testing layout looking like this:

```
.
├── composer.json
├── composer.lock
├── custom
│   └── MYMODULE
│       ├── .git
│       ├── MYMODULE.info.yml
│       └── node_modules
├── index.php
├── modules
│   └── MYMODULE -> ../custom/MYMODULE
└── vendor
```

Composer Stager choked on the `modules/MYMODULE` symlink with this error from Symfony's Filesystem component:

```
Failed to copy "/private/tmp/package_manager_testing_roottest18634147/active/custom/example" because file does not exist
```

When I told @TravisCarden about this, he said he doesn't have test coverage for symlinks _to directories_ in Composer Stager. Since we're likely to see this kind of thing in the wild, we should probably at least get test coverage for that, and hopefully find (and bust!) this bug.

**Comment by wimleers** [comment]
FYI, `composer/composer` has this interesting logic to deal with that edge case:

```
    /**
     * return true if that directory is a symlink.
     *
     * @return bool
     */
    public function isSymlinkedDirectory(string $directory)
    {
        if (!is_dir($directory)) {
            return false;
        }

        $resolved = $this->resolveSymlinkedDirectorySymlink($directory);

        return is_link($resolved);
    }
```
+
```
    /**
     * resolve pathname to symbolic link of a directory
     *
     * @param string $pathname directory path to resolve
     *
     * @return string resolved path to symbolic link or original pathname (unresolved)
     */
    private function resolveSymlinkedDirectorySymlink(string $pathname): string
    {
        if (!is_dir($pathname)) {
            return $pathname;
        }

        $resolved = rtrim($pathname, '/');

        if (0 === \strlen($resolved)) {
            return $pathname;
        }

        return $resolved;
    }
```

**Comment by TravisCarden** [comment]
Obviously, as you point out @phenaproxima, this has something to do with the Symfony Filesystem component, which doesn't support copying directories and emits that rather misleading error message, "file does not exist", if you try to copy one. I don't know if that's the only problem, but it's apparently the presenting one, and the best way to solve it is not obvious. `RecursiveFileFinder`--which true to its name, finds file, not directories--may also play a role and require refactoring.

**Comment by wimleers** [comment]
So it's not a hard blocker at the PHP language level (i.e. primitive functions such as `file_exists` and friends not behaving as they should), but rather a bug in the Symfony `Filesystem` component?

**Comment by TravisCarden** [comment]
Correct--it is _not_ a hard blocker at the PHP language level, and there's nothing preventing us from working around the problem whenever we prioritize the effort.

**Comment by TravisCarden** [comment]
@phenaproxima this has been fixed as a side effect of eliminating `PhpFileSyncer` in https://github.com/php-tuf/composer-stager/pull/334. I've removed the precondition forbidding symlinks to directories which we created in https://github.com/php-tuf/composer-stager/pull/109 and added test coverage in https://github.com/php-tuf/composer-stager/pull/336. Thanks. 🙂
